### ISSUE TITLE
Example project?

### ISSUE THREAD

**Issue by jakenuts** [dutchigor/vue-grapesjs-composables#3]
Would it be possible to add a small "hello world" project showing how to use blocks? Documentation looks great but I'm struggling with getting beyond the initial canvas.

**Comment by dutchigor** [comment]
Thanks for checking out Vue GrapesJS composables! I have published the project that I used to develop this against. See https://github.com/dutchigor/vue-grapesjs-composables-example.

Note that this project was purely for my personal testing needs so it looks terrible as there was no focus on design or usability. I'm on summer holiday right now so I don't plan on improving the example at the moment but I hope it helps you. Let me know if you have any further questions.
